### PR TITLE
chore(docs): Parameter clarification and capitalization

### PR DESCRIPTION
**Pull request by Lon3035**
Added clarification and capitalization for REST Pagination in the Docs

### CODE REVIEW

**Review by DomDew — APPROVED** [review]
Ah damn, sorry I messed this up 😅
Thanks for the fix!

**Comment by DomDew** [comment]
@all-contributors please add @Lon3035 for docs

**Comment by DomDew** [comment]
@Lon3035 could you run prettier please to fix the formatting issue? I think the version updates might have introduced some new formatting rules in the meantime.

**Comment by Lon3035** [comment]
@DomDew That's weird, my prettier says it's fine.
image

**Pull request merged**
